import turtle

turtle.setheading(225)
turtle.penup()
turtle.goto(-50, -150)
turtle.pendown()
turtle.circle(50, 270)
turtle.penup()
#base done
turtle.goto(-36, -100)
turtle.pendown()
turtle.setheading(213)
turtle.circle(40, 295)
#middle done
turtle.penup()
turtle.goto(-35,-58)
turtle.pendown()
turtle.setheading(225)
turtle.circle(30, 270)
#top done
turtle.width(0.5)
turtle.color("purple")
turtle.begin_fill()
turtle.goto(-50,-58)
turtle.goto(-50, -45)
turtle.goto(-30,-45)
turtle.goto(-30, -15)
turtle.goto(5, -15)
turtle.goto(5, -45)
turtle.goto(25, -45)
turtle.goto(25, -58)
turtle.goto(-50, -58)
turtle.end_fill()
#hat inside done
turtle.width(3)
turtle.color("green")
turtle.goto(-50,-58)
turtle.goto(-50, -45)
turtle.goto(-30,-45)
turtle.goto(-30, -15)
turtle.goto(5, -15)
turtle.goto(5, -45)
turtle.goto(25, -45)
turtle.goto(25, -58)
turtle.goto(-50, -58)
#hat outline done
turtle.color("black")
turtle.penup()
turtle.goto(-25, -75)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(0)
turtle.circle(3)
turtle.end_fill()
#left eye done
turtle.penup()
turtle.goto(-5, -75)
turtle.pendown()
turtle.begin_fill()
turtle.setheading(0)
turtle.circle(3)
turtle.end_fill()
#right eye done
turtle.penup()
turtle.goto(-30, -90)
turtle.pendown()
turtle.setheading(320)
turtle.circle(25, 80)
#mouth done
turtle.penup()
turtle.goto(-13, -125)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.circle(2)
turtle.end_fill()
#button 1 done
turtle.penup()
turtle.goto(-13, -135)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.circle(2)
turtle.end_fill()
#button 2 done
turtle.penup()
turtle.goto(-13, -145)
turtle.pendown()
turtle.color("black")
turtle.begin_fill()
turtle.circle(2)
turtle.end_fill()
#button 3 done
turtle.penup()
turtle.goto(15, -135)
turtle.pendown()
turtle.color("brown")
turtle.width(6)
turtle.goto(65, -70)
#base stick done
turtle.goto(55, -80)
turtle.goto(53, -70)
#finger 1r done
turtle.goto(55, -80)
turtle.goto(69, -83)
#finger 2r done
turtle.penup()
turtle.goto(-55 , -135)
turtle.pendown()
turtle.goto(-105, -195) 
#base stick done
turtle.goto(-95, -185)
turtle.goto(-92, -200)
#finger 1L done
turtle.goto(-95, -185)
turtle.goto(-109, -182)
turtle.hideturtle()
turtle.done()